[user]
clicks_per_loop = 15
# delay between loops in seconds
delay_between_loop_start = 10
delay_between_loop_end = 20

# delay between clicks in seconds
clicks_delay_from = 0.3
clicks_delay_to = 0.7

[app]
rpc = "https://eclipse.lgns.net"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
